# run this file with: docker image build -t rvgpu/sphinx:latest .

FROM ubuntu
LABEL maintainer="qihangkong@outlook.com"

RUN apt-get update && apt-get install -y build-essential cmake ninja-build pkg-config libdrm-dev libgtest-dev rsync
