pipeline {
    agent any

    stages {
        stage('SetUp') {
            steps {
                echo 'Set Up'
                sh "git clean -dfx"
                sh "docker image build -t rvgpu/build-csim:latest .ci/"
            }
        }
        stage('Build') {
            steps {
                echo 'Build and run unit test on docker'
                sh 'docker run --rm -v .:/source -u $(id -u):$(id -g) rvgpu/build-csim /source/.ci/release.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo 'TODO'
                sh 'ls'
            }
        }
    }
}

