# Need add instruction here
add_instruction(add)
add_instruction(addi)
add_instruction(addiw)
add_instruction(addw)
add_instruction(auipc)
add_instruction(lui)
add_instruction(sw)
add_instruction(sltu)
add_instruction(slliw)
add_instruction(slli)
add_instruction(slt)
add_instruction(jalr)
add_instruction(sd)